trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
    - script: npm install
      displayName: 'Install dependencies'
    - script: npm run build
      displayName: 'Build the application'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: 'dist'
        artifactName: 'angular-build'
    - script: npm run test
      displayName: 'Run Unit Tests'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/test-results.xml'

